apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: untappd-map
  name: untappd-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: untappd-map
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: untappd-map
    spec:
      initContainers:
      - name: untappd-map-init
        image: busybox
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget   https://github.com/lordslair/untappd-map/archive/master.zip -O /tmp/utm.zip &&
              unzip  /tmp/utm.zip -d /tmp/ &&
              cp -a  /tmp/untappd-map-master/docker/* /home/untappd-map/ &&
              rm -rf /tmp/untappd-map-master &&
              rm -rf /tmp/utm.zip
          ) || echo 1"
        ]
        volumeMounts:
        - mountPath: /home/untappd-map
          name: code

      containers:
      - name: untappd-map
        image: alpine:3.7
        command: ["/code/entrypoint.sh"]
        env:
        - name: TW_AccessTokenSecret
          valueFrom:
            secretKeyRef:
              name: untappd-map
              key: access_token_secret
        - name: TW_ConsumerSecret
          valueFrom:
            secretKeyRef:
              name: untappd-map
              key: consumer_secret
        - name: TW_AccessToken
          valueFrom:
            secretKeyRef:
              name: untappd-map
              key: access_token
        - name: TW_ConsumerKey
          valueFrom:
            secretKeyRef:
              name: untappd-map
              key: consumer_key
        volumeMounts:
        - mountPath: /home/untappd-map
          name: code
      restartPolicy: Always

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: untappd-map-code-perl
