apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: untappd-map
  name: untappd-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: untappd-map
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: untappd-map
    spec:
      restartPolicy: Always

      containers:
      - name: untappd-map
        image: alpine:3.7
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget -O - https://raw.githubusercontent.com/lordslair/untappd-map/master/docker/entrypoint.sh | sh
          ) || echo 1"
        ]
        env:
        - name: TW_AccessTokenSecret
          valueFrom:
            secretKeyRef:
              name: untappd-map
              key: access_token_secret
        - name: TW_ConsumerSecret
          valueFrom:
            secretKeyRef:
              name: untappd-map
              key: consumer_secret
        - name: TW_AccessToken
          valueFrom:
            secretKeyRef:
              name: untappd-map
              key: access_token
        - name: TW_ConsumerKey
          valueFrom:
            secretKeyRef:
              name: untappd-map
              key: consumer_key
