apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: untappd-map
  name: untappd-map-code-perl
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
