FROM alpine:3.7
MAINTAINER @Lordslair

RUN apk update \
    && apk add --no-cache perl perl-net-ssleay perl-io-socket-ssl perl-libwww librsvg \
    && apk add --no-cache --virtual .build-deps \
                                    curl make perl-dev libc-dev librsvg-dev gcc bash \
    && curl -L https://cpanmin.us | perl - App::cpanminus --no-wget \
    && cpanm --no-wget YAML::Tiny \
                       File::Pid \
                       Image::LibRSVG \
                       Net::Twitter::Lite::WithAPIv1_1 \
                       Net::OAuth \
                       Emoji::NationalFlag \
   && mkdir /untappd-map \
   && apk del .build-deps \
   && rm -rf /root/.cpanm

COPY untappd-map         /home/untappd-map/untappd-map
COPY data/               /home/untappd-map/data/
COPY lib/                /home/untappd-map/lib/
COPY test/               /home/untappd-map/test/
COPY twitter-config.yaml /home/untappd-map/

ENTRYPOINT ["/home/untappd-map/untappd-map"]
